# Generated by Django 4.0.6 on 2022-08-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='hsh_tag',
        ),
    ]
